Make GH clippy happy again
Since yesterday, clippy seems unhappy with two `prss` tests with no obvious reason why.

```
error: non-binding `let` on a type that implements `Drop`
   --> src/protocol/prss.rs:571:9
    |
571 |         let _ = p1.sequential(&step);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D clippy::let-underscore-drop` implied by `-D clippy::pedantic`
    = help: consider using an underscore-prefixed named binding or dropping explicitly with `std::mem::drop`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_underscore_drop
```

It either sees what I don't see, but I wasn't able to find `Drop` implementation for that type. I also wasn't able to reproduce it locally neither on MacOS nor Linux, despite the fact that I am using the same cargo version as our GH action

```
~/workspace/raw-ipa% ~/.cargo/bin/cargo -V
cargo 1.64.0 (387270bc7 2022-09-16)
```

I wish I could learn clippy version as well, but reading the output did not reveal it.

There was a recent change in Clippy code that touched that lint: https://github.com/rust-lang/rust-clippy/pull/9697 but I can't see how it could trigger this behaviour. To unblock us, lets appease Clippy for now